config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'page/info'

  root :to => redirect('ideas')
  resources :ideas

end

app/models/idea.rb
class Idea < ActiveRecord::Base
mount_uploader :picture, PictureUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea foi criada com sucesso.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea foi alterado com sucesso.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea foi apagada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def info
  end

def index
    @ideas = Idea.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :imagem %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editando idea</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @idea %> |
<%= link_to 'Voltar', ideas_path %>

app/views/ideas/index.html.erb
<h1>Listando ideas</h1>

<% @ideas.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |idea| %>
      <div class="span4">
      <%= image_tag idea.picture_url, :width => '33%' if idea.picture.present?%>
      <!--  <td><%= image_tag idea.picture_url(:thumb) if idea.picture? %></td> -->
        <h4><%= link_to idea.name, idea %></h4>
          <%= idea.description %>
        <br>
        <br>
        <br>
      </div>
      <% end %>
  </div>
<% end %>


<%= link_to 'Nova Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>Nova idea</h1>

<%= render 'form' %>

<%= link_to 'Volar', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

  <div class="row">
             <div class="span9">
                          <%= image_tag(@idea.picture_url, :width => "75%") if @idea.picture.present? %>
                        </div>

  <div class="span3">
    <p><b>Nome: </b><%= @idea.name %></p>
                          <p><b>Descricao: </b><%= @idea.description %></p>
                          <p>
                            <%= link_to 'Editar', edit_idea_path(@idea) %>
                            <%= button_to 'Apagar', idea_path(@idea), confirm: 'Voce esta certo?', method: :delete %>
      <%= link_to 'Voltar', ideas_path %>
                          </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Girls</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css" />
<link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css" />

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= yield %>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
</div>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Aplicativo Das Ideas</a>
    </div>
    <div class="collapse navbar-collapse">
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logado como <strong><%= current_user.email %></strong> -
  <%= link_to 'Editar Conta', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Criar Conta", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

      <ul class="nav navbar-nav">
        <li class="active"><a href="/ideas">Ideas</a></li>
        <li ><% link_to "Nova Idea", new_idea_path %></li>
      </ul>
    </div>
  </div>
</nav>
</body>

<footer>
  <div class="container">
    Rails Girls 2014
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>
</html>

app/views/page/info.html.erb
<h1>Page#info</h1>
<p>Find me in app/views/page/info.html.erb</p>
<h1>Essa pagina eh de inforamacao sobre o sistema</h1>
<br>
<p>Teste de dados de informacoes<p>
<p><b>Nome: </b><%= Idea.find_by(id: '6').name %></p>